services:
  backend:
    container_name: fast_api_app
    ports: 
      - 8081:8081
    volumes: 
      - ./fast-api-app:/fast-api-app:cached
    working_dir: /fast-api-app # 作業ディレクトリ指定
    build: 
      context: .
      dockerfile: ./dockerfiles/fast-api/Dockerfile
    tty: true
    restart: always
    environment:
      - FAST_DATASOURCE_URL=jdbc:postgres://db:5432/try_db
      - FAST_DATASOURCE_URL_DATASOURCE_USERNAME=postgres
      - FAST_DATASOURCE_PASSWORD=postgres